.TH smt-metadata 1 "2026-05-29" "0.1.0" "SMT User Manual"
.SH NAME
.PP
smt-metadata \- SMT metadata editor
.SH SYNOPSIS
.PP
smt-metadata [\fB\-v\fR|\fB\-\-verbose\fR \fI<VERBOSE>\fR]
             [\fB\-h\fR|\fB\-\-help\fR]
             [\fB\-V\fR|\fB\-\-version\fR]
             \fI<AUDIO_FILE_PATH>\fR
             \fI<COMMAND>\fR [\fI<COMMAND_OPTIONS>\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag clear

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag set \fI<KEY>\fR \fI<VALUE>\fI [\fI<VALUE>\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag append \fI<KEY>\fR \fI<VALUE>\fI [\fI<VALUE>\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag remove \fI<KEY>\fR

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag list
             [\fB\-\-json\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             tag edit
             [\fB\-\-editor\fR \fI<PATH>\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             cover export
             [\fB\-o\fR|\fB\-\-output\fR \fI<PATH>\fR]

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             cover remove

smt-metadata [\fI<OPTIONS>\fR]
             \fI<AUDIO_FILE_PATH>\fR
             cover set \fI<COVER_PATH>\fR


.SH DESCRIPTION
.PP
.B smt-metadata
enables editing of Vorbis and IDv3 metadata, as well as embedded cover images,
in audio files.

.SH COMMANDS
.TS
tab(@);
lB lx.
tag clear@T{
Clears all metadata tags from the audio file.
T}

tag set <KEY> [<VALUE>]@T{
Overrides existing metadata tags with new values, avoiding case-sensitive
duplicates.
T}

tag append <KEY> [<VALUE>]@T{
Appends new metadata tag values to the audio file, avoiding case-sensitive
duplicates.
T}

tag remove <KEY>@T{
Removes specified metadata tags from the audio file.
T}

tag list@T{
Lists existing tags on the audio file.
T}

tag edit@T{
Starts an interactive session for bulk editing via a text editor.
T}

cover export@T{
Extracts the cover image from the audio file (if available).
T}

cover set <PATH>@T{
Sets a cover image for the audio file. Only JPEG and PNG formats are supported.
Additionally, a cover image from another audio file can be used as the source.
T}

cover remove@T{
Removes the cover image from the audio file (if available).
T}
.TE

.SH OPTIONS
.SS GLOBAL OPTIONS
.TP
.BR \-v ", " \-\-verbose
Set verbosity level. Allowed values are
.BR full ", " default ", " quiet
.TP
.BR \-h ", " \-\-help
Print help menu and exit.
.TP
.BR \-V ", " \-\-version
Print version and exit.

.SS TAG LIST OPTIONS
.TP
.BR \-\-json
Enable printing metadata as JSON formatted text.
.TP

.SS TAG EDIT OPTIONS
.TP
.BR \-\-editor\ <NAME|PATH>
Overrides the default text editor. If the provided value is not a path,
the \fIPATH\fR environment variable is used to locate the executable.
.TP

.SS COVER EXPORT OPTIONS
.TP
.BR \-o ", " \-\-output " " <PATH>
Set output directory or path. By default exports to current directory as 
\fIcover.(jpg|png)\fR.
.TP

.SH ENVIRONMENT
.SS EDITOR
.TP
Text editor used by \fBtag edit\fR command. If not set, uses \fBvi\fR(1) as 
fallback option.

.SH EXAMPLE

.SS
Metadata operations

.TP
Append new artists:

.EX
smt-metadata /path/to/audio.flac tag append ARTIST "Tim Vegas" "Chen-U"
.EE

.TP
Set date:

.EX
smt-metadata /path/to/audio.flac tag set DATE "2012-04-01"
.EE

.TP
Remove comment tags:

.EX
smt-metadata /path/to/audio.flac tag remove COMMENT
.EE

.TP
List tags as JSON and use \fBjq\fR(1) for formatting:

.EX
smt-metadata /path/to/audio.flac tag list --json | jq
.EE

.TP
Edit all tags with different text editor:

.EX
smt-metadata /path/to/audio.flac tag edit --editor nvim
.EE

.SS 
Cover image operations

.TP
Remove cover image:

.EX
smt-metadata /path/to/audio.flac cover remove
.EE

.TP
Set cover image:

.EX
smt-metadata /path/to/audio.flac cover set /path/to/cover.jpg
.EE

.TP
Set cover image from another audio file with embedded cover image:

.EX
smt-metadata /path/to/audio.flac cover set /path/to/another.flac
.EE

.TP
Export cover image to specific directory:

.EX
smt-metadata /path/to/audio.flac cover export -o /images/
.EE

.TP
Export cover image to specific path:

.EX
smt-metadata /path/to/audio.flac cover export -o /images/my-cover.jpg
.EE

.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Usage or invalid file formats.

.SH BUGS

.B smt-metadata
is primarily tested against FFmpeg version n8.1.1. Depending on how the tool
was built, the linked libavformat and libavcodec libraries may missing certain
decoders, unexpected metadata behavior, or contain other kind of bugs.

For MP3 files; FFmpeg can write multi-value metadata tags without an issue, but
current implementation fails to read all available tags.

.SH REPORTING BUGS
.TS
tab(%);
lB lx.

Codeberg%https://codeberg.org/SuperiorOne/smt/issues
Github%https://github.com/SuperioOne/smt/issues
Email%pm@smdd.dev
.TE

.SH SEE ALSO
.BR smt (7)
