.TH smt-parse 1 "2026-05-26" "0.1.0" "SMT User Manual"
.SH NAME
.PP
smt-parse \- SMT cuesheet parser
.SH SYNOPSIS
.PP
smt-parse [\fB\-i\fR|\fB\-\-input\fR \fI<PATH>\fR]
          [\fB\-v\fR|\fB\-\-verbose\fR \fI<VERBOSE>\fR]
          [\fB\-h\fR|\fB\-\-help\fR]
          [\fB\-V\fR|\fB\-\-version\fR]
          \fI<COMMAND>\fR
          [\fI<SUBOPTIONS>\fR]
.SH DESCRIPTION
.PP
.B smt-parse
provides basic utility for converting and testing CDRWIN's cuesheet files.

.SH COMMANDS
.TS
tab(@);
l lx.
\fBtest\fR@T{
Verifies input cuesheet format.
T}
\fBconvert-json\fR@T{
Converts input cuesheet into JSON output.
T}
.TE

.SH OPTIONS
.SS Global options:
.TP
.BR \-i ", " \-\-input
Set cuesheet input file path. If not set, \fBstdin(3)\fR is used as cuesheet input.
.TP
.BR \-v ", " \-\-verbose
Set verbosity level. Allowed values are
.BR full ", " default ", " quiet
.TP
.BR \-h ", " \-\-help
Print help menu and exit.
.TP
.BR \-V ", " \-\-version
Print version and exit.

.SS \fBconvert-json\fR options:
.TP
.BR \-o ", " \-\-output
Set JSON output file path. If not set, \fBstdout(3)\fR is used as output.
.TP
.BR \-m ", " \-\-metadata
Enable parsing of additional Vorbis comments from cuesheet remarks.
.IP
For more details about how Vorbis comments are parsed from remarks see \fBsmt\fR(7).
.TP
.BR \-p ", " \-\-pretty-print
Format JSON output.

.SH EXAMPLE

.SS
Testing cuesheets

.TP
Using an input file:

.EX
smt-parse -i example.cue test
.EE

.TP
Piping input file:

.EX
cat example.cue | smt-parse test
.EE

.TP
Getting detailed parse errors:

.EX
smt-parse --verbose full -i example.cue test
.EE

.SS
Converting cuesheets to JSON:

.TP
Using an input file with Vorbis metadata and pretty print enabled:

.EX
smt-parse -i example.cue convert-json -mp
.EE

.TP
Using \fBjq\fR(1) to query track titles:

.EX
smt-parse -i example.cue convert-json -m | jq '.tracks[].title'
.EE

.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Usage or invalid cuesheet errors.

.SH REPORTING BUGS
.TS
tab(%);
l lx.

\fBCodeberg\fR%https://codeberg.org/SuperiorOne/smt/issues
\fBGithub\fR%https://github.com/SuperioOne/smt/issues
\fBEmail\fR%pm@smdd.dev
.TE

.SH SEE ALSO
.BR smt-split (1),
.BR smt (7),
.BR jq (1)
