.TH smt-split 1 "2026-05-26" "0.1.0" "SMT User Manual"
.SH NAME
.PP
smt-split \- SMT cuesheet split
.SH SYNOPSIS
.PP
smt-split [\fB\-i\fR|\fB\-\-input\fR \fI<PATH>\fR]
          [\fB\-f\fR|\fB\-\-file-path\fR \fI<PATH>\fR]
          [\fB\-o\fR|\fB\-\-output-dir\fR \fI<PATH>\fR]
          [\fB\-m\fR|\fB\-\-metadata\fR]
          [\fB\-v\fR|\fB\-\-verbose\fR \fI<VERBOSE>\fR]
          [\fB\-h\fR|\fB\-\-help\fR]
          [\fB\-V\fR|\fB\-\-version\fR]
.SH DESCRIPTION
.PP
.B smt-split
splits audio files into individual tracks, automatically trims track
pregaps (INDEX 00), and applies all available metadata to each track
by using cuesheet.

.PP
The tool internally uses \fIlibavformat\fR and \fIlibavcodec\fR,
enabling support for a wide range of audio codecs and container
formats. It is specifically designed for splitting audio via
cuesheets; for format transcoding, use \fBffmpeg\fR(1) instead.

.SH OPTIONS
.TP
.BR \-i ", " \-\-input
Set cuesheet input file path. If not set, \fBstdin(3)\fR is used as cuesheet
input.
.TP
.BR \-v ", " \-\-verbose
Set verbosity level. Allowed values are
.BR full ", " default ", " quiet
.TP
.BR \-f ", " \-\-file-path
If given path is a file, overrides FILE command with the given path.

If given path is a directory, uses it as a root directory for cuesheet FILE
command.

By default, uses cuesheet's parent directory.
.TP
.BR \-o ", " \-\-output-dir
Set output directory for the splitted tracks.

This option automatically creates parent directories if they do not exists.

By default, uses current directory.
.TP
.BR \-m ", " \-\-metadata
Enable additional Vorbis comments from cuesheet remarks.
.IP
For more details about how Vorbis comments are parsed from remarks, see
\fBsmt\fR(7).
.TP
.BR \-h ", " \-\-help
Print help menu and exit.
.TP
.BR \-V ", " \-\-version
Print version and exit.

.SH EXAMPLE

.SS Basic splitting:

.TS
tab(@);
l lx.
\fBCUE\fR@T{
"./example.cue"
T}
\fBAUDIO\fR@T{
"./example.wav"
T}
.TE

.EX
smt-split -m -i example.cue
.EE

.SS Splitting from different directory:

.TS
tab(@);
l lx.
\fBCUE\fR@T{
"/path/to/example.cue"
T}
\fBAUDIO\fR@T{
"/path/to/example.wav"
T}
.TE

.EX
smt-split -m -i /path/to/example.cue
.EE

.SS Overriding FILE directory:

.TS
tab(@);
l lx.
\fBCUE\fR@T{
"/path/to/example.cue"
T}
\fBAUDIO\fR@T{
"/path/different/example.wav"
T}
.TE

.EX
smt-split -m -i /path/to/example.cue -f /path/different/
.EE

.SS Overriding FILE path:

.TS
tab(@);
l lx.
\fBCUE\fR@T{
"/path/to/example.cue"
T}
\fBAUDIO\fR@T{
"/path/different/target.flac"
T}
.TE

.EX
smt-split -m -i /path/to/example.cue -f /path/different/target.flac
.EE

.SS Custom output directory:

.EX
smt-split -m -i example.cue -o /tmp/album/
.EE

.SH EXIT STATUS
.TP
.B 0
Successful program execution.
.TP
.B 1
Usage, encoder, decoder, or invalid cuesheet errors.

.SH BUGS

.B smt-split
is primarily tested against FFmpeg version n8.1.1. Depending on how the tool
was built, the linked libavformat and libavcodec libraries may missing certain
encoders, different behavior, or contain other kind of bugs.

.SH REPORTING BUGS
.TS
tab(%);
l lx.

\fBCodeberg\fR%https://codeberg.org/SuperiorOne/smt/issues
\fBGithub\fR%https://github.com/SuperioOne/smt/issues
\fBEmail\fR%pm@smdd.dev
.TE

.SH SEE ALSO
.BR smt-parse (1),
.BR smt (7),
.BR ffmpeg (1)
