[package]
name = "smt_ffmpeg"
description = "libav API with some additional wrapper data types and functions"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
vendored_static = [ "smt_ffmpeg_sys/vendored_static" ]
vendored_dynamic = [ "smt_ffmpeg_sys/vendored_dynamic" ]

[dependencies]
smt_ffmpeg_sys.workspace = true
