[package]
name = "smt_ffmpeg_src"
description = "provides basic utility to build ffmpeg libav from the source"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
