[package]
name = "smt-parse"
description = "cuesheet parse tool"
keywords = ["cue", "cuesheet", "file-format", "cli", "cli-tool"]
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
version.workspace = true

[dependencies]
clap.workspace = true
smt_common.workspace = true
cue_lib = { workspace = true, features = ["metadata", "alloc", "serde"] }
serde.workspace = true
serde_json.workspace = true
