[package]
name = "smt-split"
description = "splits common audio formats by using cuesheet information"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = false
repository.workspace = true
version.workspace = true

[features]
default = []
vendored_static = [ "smt_ffmpeg/vendored_static" ]
vendored_dynamic = [ "smt_ffmpeg/vendored_dynamic" ]

[dependencies]
clap.workspace = true
smt_ffmpeg.workspace = true
smt_common.workspace = true
cue_lib = { workspace = true, features = ["metadata", "alloc"] }
